#!/usr/bin/env python3
"""Generate and check CARE architecture wiki diagram artifacts from YAML/CSV."""

from __future__ import annotations

import argparse
import csv
import hashlib
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


FIGURES = ("model-current", "model-gap", "execution-flow")


def run(cmd: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=cwd, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)


def parse_architecture(text: str) -> tuple[list[dict[str, str]], list[dict[str, str]], dict[str, str]]:
    nodes: list[dict[str, str]] = []
    edges: list[dict[str, str]] = []
    meta: dict[str, str] = {}
    section = ""
    current: dict[str, str] | None = None
    for raw in text.splitlines():
        line = raw.rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        top = line.split(":", 1)
        if not line.startswith(" ") and len(top) == 2:
            key = top[0].strip()
            value = top[1].strip()
            if key in {"nodes", "edges"}:
                section = key
                current = None
            else:
                meta[key] = value.strip("\"'")
            continue
        item = line.strip()
        if item.startswith("- "):
            current = {}
            if section == "nodes":
                nodes.append(current)
            elif section == "edges":
                edges.append(current)
            item = item[2:]
        if current is not None and ":" in item:
            key, value = item.split(":", 1)
            current[key.strip()] = value.strip().strip("\"'")
    return nodes, edges, meta


def read_components(path: Path) -> dict[str, dict[str, str]]:
    if not path.is_file():
        return {}
    rows = csv.DictReader(path.read_text(encoding="utf-8").splitlines())
    return {row.get("component_id", ""): row for row in rows if row.get("component_id")}


def q(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def status_style(status: str, evidence: str = "") -> str:
    status = status.lower()
    evidence = evidence.lower()
    if status in {"legacy", "disabled"}:
        return "style.stroke: \"#6b7280\"\n  style.fill: \"#f3f4f6\""
    if status in {"partial", "scaffold"} or evidence in {"unverified", "stale", "missing"}:
        return "style.stroke-dash: 5\n  style.fill: \"#fff7e6\""
    if status == "implemented" and evidence == "verified":
        return "style.fill: \"#e8f5e9\""
    return "style.stroke-dash: 3\n  style.fill: \"#eef1f8\""


def component_for_node(node: dict[str, str], components: dict[str, dict[str, str]]) -> dict[str, str]:
    node_id = node.get("id", "")
    if node_id in components:
        return components[node_id]
    for row in components.values():
        if node_id in row.get("component_id", "") or node_id in row.get("role", "").lower().replace(" ", "_"):
            return row
    return {}


def provenance(meta: dict[str, str], arch_text: str, comp_text: str) -> str:
    digest = hashlib.sha256((arch_text + "\n" + comp_text).encode("utf-8")).hexdigest()[:16]
    return (
        f"generated_from: architecture.yaml + COMPONENTS.csv\\n"
        f"review_token: {meta.get('review_token', 'UNKNOWN')}\\n"
        f"source_hash: {digest}"
    )


def render_model_current(nodes: list[dict[str, str]], edges: list[dict[str, str]], components: dict[str, dict[str, str]], meta_text: str) -> str:
    required = [
        ("inputs", "LGE / C0 / T2 输入\\navailability mask"),
        ("stems", "模态专属\\nstems/encoders"),
        ("retrieval", "shared/private/interaction\\n检索字典"),
        ("anatomy", "解剖先验\\nLV/RV/union"),
        ("scar_proposal", "scar proposal"),
        ("scar_refiner", "scar soft-ROI refiner"),
        ("edema_proposal", "edema proposal"),
        ("edema_refiner", "edema soft-ROI refiner"),
        ("no_t2_safety", "no-T2 edema\\n安全门"),
        ("losses", "loss/objective groups"),
        ("nnunet", "nnU-Net context/evidence\\nanchor 边界"),
        ("final_logits", "final logits\\n与 labels"),
        ("cine", "Cine 分支\\n独立次线"),
    ]
    lines = [
        "# Generated by scripts/architecture/generate_care_architecture_wiki.py",
        "direction: right",
        f"meta: \"{q(meta_text)}\"",
    ]
    for node_id, label in required:
        source_node = next((node for node in nodes if node.get("id") == node_id), {})
        comp = component_for_node(source_node or {"id": node_id}, components)
        status = source_node.get("current_status") or comp.get("current_status", "unknown")
        evidence = comp.get("evidence_status", "unverified")
        lines.append(f'{node_id}: "{q(label)}" {{')
        lines.append("  " + status_style(status, evidence).replace("\n", "\n  "))
        lines.append("}")
    lines.extend(
        [
            "inputs -> stems: 可用性通道",
            "stems -> retrieval: 语义特征",
            "retrieval -> scar_proposal",
            "retrieval -> edema_proposal",
            "anatomy -> scar_proposal",
            "anatomy -> edema_proposal",
            "scar_proposal -> scar_refiner",
            "edema_proposal -> edema_refiner",
            "scar_refiner -> final_logits",
            "edema_refiner -> no_t2_safety",
            "no_t2_safety -> final_logits",
            "losses -> retrieval: 训练目标",
            "nnunet -> final_logits: anchor/context/safety",
            "cine -> final_logits: local proxy evidence",
        ]
    )
    return "\n".join(lines) + "\n"


def render_model_gap(nodes: list[dict[str, str]], components: dict[str, dict[str, str]], meta_text: str) -> str:
    lines = [
        "# Generated by scripts/architecture/generate_care_architecture_wiki.py",
        "direction: down",
        f"meta: \"{q(meta_text)}\"",
    ]
    for node in nodes:
        node_id = node.get("id", "node")
        comp = component_for_node(node, components)
        current = comp.get("current_status") or node.get("current_status", "unknown")
        target = comp.get("target_status") or node.get("target_status", "unknown")
        evidence = comp.get("evidence_status", "unverified")
        label = f"{node.get('label', node_id)}\\n当前: {current}\\n目标: {target}\\n证据: {evidence}"
        lines.append(f'{node_id}: "{q(label)}" {{')
        lines.append("  " + status_style(current, evidence).replace("\n", "\n  "))
        lines.append("}")
    return "\n".join(lines) + "\n"


def render_execution_flow(meta_text: str) -> str:
    lines = [
        "# Generated by scripts/architecture/generate_care_architecture_wiki.py",
        "direction: right",
        f"meta: \"{q(meta_text)}\"",
        'planner: "规划者\\nGPT task contract"',
        'controller: "controller\\nphase grounding"',
        'executor: "executor wave(s)\\nimplementation/jobs"',
        'mapper_draft: "mapper draft\\n架构快照"',
        'finalizer_a: "FINALIZER_A\\nSlurm accounting + aggregation"',
        'mapper_final: "mapper final\\nwiki/evidence reconciliation"',
        'finalizer_b: "FINALIZER_B\\nvalidators + local commit"',
        'reviewer: "独立 reviewer\\nreview.md"',
        'planner -> controller',
        'controller -> executor',
        'executor -> mapper_draft: implementation snapshot',
        'mapper_draft -> finalizer_a: job ids + runtime paths',
        'finalizer_a -> mapper_final: tracked evidence',
        'mapper_final -> finalizer_b',
        'finalizer_b -> reviewer: committed final packet',
    ]
    return "\n".join(lines) + "\n"


def generated_sources(repo_root: Path) -> dict[str, str]:
    arch_path = repo_root / "wiki" / "architecture.yaml"
    comp_path = repo_root / "wiki" / "COMPONENTS.csv"
    arch_text = arch_path.read_text(encoding="utf-8")
    comp_text = comp_path.read_text(encoding="utf-8")
    nodes, edges, meta = parse_architecture(arch_text)
    components = read_components(comp_path)
    meta_text = provenance(meta, arch_text, comp_text)
    return {
        "model-current": render_model_current(nodes, edges, components, meta_text),
        "model-gap": render_model_gap(nodes, components, meta_text),
        "execution-flow": render_execution_flow(meta_text),
    }


def generated_history_sources(repo_root: Path, version: str) -> dict[str, str]:
    base = repo_root / "wiki" / "history" / version
    arch_path = base / "architecture.yaml"
    comp_path = base / "COMPONENTS.csv"
    arch_text = arch_path.read_text(encoding="utf-8")
    comp_text = comp_path.read_text(encoding="utf-8")
    nodes, edges, meta = parse_architecture(arch_text)
    components = read_components(comp_path)
    meta_text = provenance(meta, arch_text, comp_text)
    architecture_lines = [
        "# Generated by scripts/architecture/generate_care_architecture_wiki.py",
        "direction: right",
        f"meta: \"{q(meta_text)}\"",
    ]
    for node in nodes:
        comp = component_for_node(node, components)
        status = comp.get("current_status") or node.get("current_status", "unknown")
        evidence = comp.get("evidence_status", "unverified")
        architecture_lines.append(f'{node["id"]}: "{q(node.get("label", node["id"]))}" {{')
        architecture_lines.append("  " + status_style(status, evidence).replace("\n", "\n  "))
        architecture_lines.append("}")
    for edge in edges:
        architecture_lines.append(f'{edge.get("from")} -> {edge.get("to")}: {q(edge.get("condition", edge.get("kind", "")))}')
    gap_lines = [
        "# Generated by scripts/architecture/generate_care_architecture_wiki.py",
        "direction: down",
        f"meta: \"{q(meta_text)}\"",
    ]
    for node in nodes:
        comp = component_for_node(node, components)
        label = f"{node.get('label', node['id'])}\\n当前: {comp.get('current_status', node.get('current_status', 'unknown'))}\\n目标: {comp.get('target_status', node.get('target_status', 'unknown'))}\\n证据: {comp.get('evidence_status', 'unverified')}"
        gap_lines.append(f'{node["id"]}: "{q(label)}"')
    sources = {"architecture": "\n".join(architecture_lines) + "\n", "gap": "\n".join(gap_lines) + "\n"}
    if version != "M08":
        delta = [
            "# Generated by scripts/architecture/generate_care_architecture_wiki.py",
            "direction: right",
            f"meta: \"{q(meta_text)}\"",
            'm08: "M08\\nanchor-centered diagnostic"',
            f'{version.lower()}: "{version}\\nSRR-main no-promotion diagnostic"',
            f'm08 -> {version.lower()}: "状态变化与证据收紧"',
        ]
        sources["delta-from-M08"] = "\n".join(delta) + "\n"
    return sources


def render_outputs(repo_root: Path, stem: str, d2_path: Path, svg_path: Path, png_path: Path) -> list[str]:
    errors: list[str] = []
    d2 = shutil.which("d2")
    if not d2:
        return ["d2 executable not found"]
    convert = shutil.which("convert")
    cp = run([d2, str(d2_path), str(svg_path)], repo_root)
    if cp.returncode != 0:
        return [f"d2 svg render failed for {stem}: {cp.stderr.strip() or cp.stdout.strip()}"]
    cp = run([d2, str(d2_path), str(png_path)], repo_root)
    if cp.returncode == 0:
        return errors
    if not convert:
        return [f"d2 png render failed for {stem} and ImageMagick convert is unavailable: {cp.stderr.strip()}"]
    cp2 = run([convert, str(svg_path), str(png_path)], repo_root)
    if cp2.returncode != 0:
        errors.append(
            f"png render failed for {stem}: d2={cp.stderr.strip() or cp.stdout.strip()}; "
            f"convert={cp2.stderr.strip() or cp2.stdout.strip()}"
        )
    return errors


def check(repo_root: Path, sources: dict[str, str], figure_dir: Path | None = None) -> list[str]:
    errors: list[str] = []
    figure_dir = figure_dir or repo_root / "wiki" / "figures"
    for stem, source in sources.items():
        d2_path = figure_dir / f"{stem}.d2"
        svg_path = figure_dir / f"{stem}.svg"
        png_path = figure_dir / f"{stem}.png"
        if not d2_path.is_file():
            errors.append(f"missing generated D2 source: {d2_path}")
            continue
        if d2_path.read_text(encoding="utf-8") != source:
            errors.append(f"stale generated D2 source: {d2_path}")
        for output in (svg_path, png_path):
            if not output.is_file():
                errors.append(f"missing rendered artifact: {output}")
            elif output.stat().st_mtime < d2_path.stat().st_mtime:
                errors.append(f"rendered artifact older than generated D2 source: {output}")
    return errors


def write_and_render(repo_root: Path, sources: dict[str, str], figure_dir: Path | None = None) -> list[str]:
    figure_dir = figure_dir or repo_root / "wiki" / "figures"
    figure_dir.mkdir(parents=True, exist_ok=True)
    errors: list[str] = []
    for stem, source in sources.items():
        d2_path = figure_dir / f"{stem}.d2"
        svg_path = figure_dir / f"{stem}.svg"
        png_path = figure_dir / f"{stem}.png"
        d2_path.write_text(source, encoding="utf-8")
        errors.extend(render_outputs(repo_root, stem, d2_path, svg_path, png_path))
    return errors


def process_history(repo_root: Path, version: str, check_only: bool) -> list[str]:
    figure_dir = repo_root / "wiki" / "history" / version / "figures"
    sources = generated_history_sources(repo_root, version)
    return check(repo_root, sources, figure_dir) if check_only else write_and_render(repo_root, sources, figure_dir)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check current artifacts without writing.")
    parser.add_argument("--current", action="store_true", help="Generate/check current wiki figures.")
    parser.add_argument("--history", choices=("M08", "M09"), help="Generate/check one history version.")
    parser.add_argument("--check-all", action="store_true", help="Check current and all history versions.")
    args = parser.parse_args(argv)

    repo_root = Path.cwd()
    required_inputs = [repo_root / "wiki" / "architecture.yaml", repo_root / "wiki" / "COMPONENTS.csv"]
    errors = [f"missing required input: {path}" for path in required_inputs if not path.is_file()]
    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        return 1

    if args.check_all:
        errors = check(repo_root, generated_sources(repo_root))
        for version in ("M08", "M09"):
            errors.extend(process_history(repo_root, version, True))
    elif args.history:
        errors = process_history(repo_root, args.history, args.check)
    else:
        sources = generated_sources(repo_root)
        errors = check(repo_root, sources) if args.check else write_and_render(repo_root, sources)
    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        return 1
    print("care architecture wiki diagrams ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
