"""nnU-Net trainers for the 20260801 target-domain pathology race."""

from __future__ import annotations

import json
from pathlib import Path

import torch
from nnunetv2.training.nnUNetTrainer.variants.training_length.nnUNetTrainer_Xepochs import nnUNetTrainer_500epochs


REPO_ROOT = Path(__file__).resolve().parents[3]
RESULT_ROOT = REPO_ROOT / "results/20260801_care_target_domain_pathology_specialist_race"


class nnUNetTrainerTargetDomainRace4000(nnUNetTrainer_500epochs):
    """Complete-trimodal target-domain fine-tune for fold2/fold3.

    The actual fold-specific train/inner split is generated by
    `scripts/target_domain_race/bootstrap_target_domain_race.py`. We keep the
    stock nnU-Net architecture and loss and only override data membership and
    the training budget.
    """

    def __init__(
        self,
        plans: dict,
        configuration: str,
        fold: int,
        dataset_json: dict,
        device: torch.device = torch.device("cuda"),
    ) -> None:
        super().__init__(plans, configuration, fold, dataset_json, device)
        self.num_iterations_per_epoch = 250
        self.num_val_iterations_per_epoch = 50
        self.num_epochs = 16
        self.save_every = 2

    def do_split(self):
        split = json.loads((RESULT_ROOT / "split_receipt.json").read_text(encoding="utf-8"))
        key = f"fold{int(self.fold)}"
        if key not in split:
            raise RuntimeError(f"target-domain race split receipt does not contain {key}")
        tr_keys = list(split[key]["actual_train_cases"])
        val_keys = list(split[key]["inner_selection_cases"])
        self.print_to_log_file(
            f"Using target-domain race complete-trimodal split for {key}: "
            f"{len(tr_keys)} actual-train, {len(val_keys)} inner-selection"
        )
        return tr_keys, val_keys
