#!/usr/bin/env python3
"""Repository wrapper for the Chinese/math PDF header generator.

The CARE migrated /users copy has a namespace-local render bundle with xeCJK,
ctex, Noto CJK, and Fandol.  For final-standard CARE PDFs, prefer the bundled
Noto CJK fonts so the output remains viewer-compatible without using the system
Droid fallback.
"""

from __future__ import annotations

import argparse
import runpy
from pathlib import Path

SCRIPT = Path("/users/a/e/aereinh/.codex-global/skills/tools-documents-media-render-chinese-math-pdf/scripts/build_chinese_math_header.py")
RESOURCE_DIR = Path("/users/a/e/aereinh/render_resources/chinese_math_pdf")


def write_care_header(output: Path) -> bool:
    noto = RESOURCE_DIR / "texmf/fonts/opentype/public/noto-cjk"
    if not (noto / "NotoSerifSC-Regular.otf").exists() or not (noto / "NotoSansSC-Regular.otf").exists():
        return False
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        r"""% Generated by scripts/build_chinese_math_header.py for CARE.
% Use with Pandoc --pdf-engine=xelatex.
\usepackage{fontspec}
\usepackage{xeCJK}
\usepackage{amsmath,amssymb}
\usepackage{booktabs,longtable,array}
\usepackage{graphicx}
\usepackage{hyperref}
\hypersetup{colorlinks=true,linkcolor=blue,urlcolor=blue,citecolor=blue}
\XeTeXlinebreaklocale "zh"
\XeTeXlinebreakskip = 0pt plus 1pt
\setmainfont[
  Path={/usr/share/texlive/texmf-dist/fonts/opentype/public/tex-gyre/},
  BoldFont={texgyretermes-bold.otf},
  ItalicFont={texgyretermes-italic.otf},
  BoldItalicFont={texgyretermes-bolditalic.otf}
]{texgyretermes-regular.otf}
\setmonofont[
  Path={/usr/share/texlive/texmf-dist/fonts/opentype/public/tex-gyre/},
  BoldFont={texgyrecursor-bold.otf},
  ItalicFont={texgyrecursor-italic.otf},
  BoldItalicFont={texgyrecursor-bolditalic.otf}
]{texgyrecursor-regular.otf}
\setCJKmainfont[
  Path={/users/a/e/aereinh/render_resources/chinese_math_pdf/texmf/fonts/opentype/public/noto-cjk/},
  BoldFont={NotoSerifSC-Bold.otf}
]{NotoSerifSC-Regular.otf}
\setCJKsansfont[
  Path={/users/a/e/aereinh/render_resources/chinese_math_pdf/texmf/fonts/opentype/public/noto-cjk/},
  BoldFont={NotoSansSC-Bold.otf}
]{NotoSansSC-Regular.otf}
\setCJKmonofont[
  Path={/users/a/e/aereinh/render_resources/chinese_math_pdf/texmf/fonts/opentype/public/noto-cjk/},
  BoldFont={NotoSansSC-Bold.otf}
]{NotoSansSC-Regular.otf}
""",
        encoding="utf-8",
    )
    return True

if __name__ == "__main__":
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--root")
    parser.add_argument("--output", type=Path)
    args, _ = parser.parse_known_args()
    if args.output and write_care_header(args.output):
        raise SystemExit(0)
    runpy.run_path(str(SCRIPT), run_name="__main__")
